### ISSUE TITLE
更换IP地址检测API

### ISSUE THREAD

**Issue by GenshinMinecraft** [nodecook/agent#7]
请更换更加准确的国内IP 地址数据库，如 cz88.net
比如我的 IP 被检测为 
🇨🇳 中国 / Guangdong / Guangzhou

实际上是

🇨🇳 中国 / Guangxi / Wuzhou

**Comment by nodecook-dev** [comment]
有推荐的吗？目前使用的是 ipinfo.io 的免费 api。

**Comment by nodecook-dev** [comment]
我看看 cz88.net

**Comment by GenshinMinecraft** [comment]
cz88.net是国内最准的

**Comment by GenshinMinecraft** [comment]
ipinfo很炸裂，我的中国移动飞到了加拿大移动

**Comment by GenshinMinecraft** [comment]
还有，如果可以，建议让后端贡献者自行填写规范格式化的地域信息，不过可能会导致一些问题

**Comment by nodecook-dev** [comment]
> 还有，如果可以，建议让后端贡献者自行填写规范格式化的地域信息，不过可能会导致一些问题

地区信息精确到城市级别的i18n不太好搞

**Comment by GenshinMinecraft** [comment]
这是一个好问题，我能想到的解决方法好像只有一个个对应

**Comment by nodecook-dev** [comment]
> 请更换更加准确的国内IP 地址数据库，如 cz88.net 比如我的 IP 被检测为 🇨🇳 中国 / Guangdong / Guangzhou
> 
> 实际上是
> 
> 🇨🇳 中国 / Guangxi / Wuzhou

顺便问下，是检测节点信息还是检测目标信息不对？

**Comment by GenshinMinecraft** [comment]
是节点信息，目标信息如果使用的也是ipinfo 的API 的话，国内基本上不太对的

**Comment by nodecook-dev** [comment]
> 是节点信息，目标信息如果使用的也是ipinfo 的API 的话，国内基本上不太对的

好吧，但是现在项目本身没啥收益，可能暂时也不会上付费方案

**Comment by GenshinMinecraft** [comment]
也有比较好的免费api的，也可以让贡献者自行上传地区信息
